# Two services: backend API on 5000, frontend (nginx) on 80
services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env        # provided on EC2, not committed
    ports:
      - "5000:5000"

  frontend:
    build: ./client
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
