version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: frontend
    restart: always
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
